### ISSUE TITLE
Add End Time to Event Model

### ISSUE THREAD

**Issue by jadekeegan** [unc-csxl/csxl.unc.edu#132]
# Add End Time to Event Model
Add an end time to the Event model and entity, and display it on the frontend.

## Why?
There is currently no way to set and display end times for events, which is an important feature for ensuring that users have complete information about events.

## Acceptance Criteria
- [x] Update the Event model, entity, dev data, and test data to include an end time.
- [x] Update the front end to display Event end time

**Comment by briannata** [comment]
- [ ] Add validator that makes sure end time is after start time

How do we want to handle multi-day events?
