### ISSUE TITLE
Resolve HTML Linter Bug

### ISSUE THREAD

**Issue by jadekeegan** [unc-csxl/csxl.unc.edu#147]
# Resolve HTML Linter Bug
The linter occasionally autoformats the HTML in a way that produces an error in the code. One instance of this occurring is in the Organization Details Info Card Widget HTML file around line 35.

Fixed Line of Code:
![Image](https://github.com/unc-csxl/csxl.unc.edu/assets/97476936/2f78bd82-fcf7-4360-a417-fc18248775d6)

After Save & Linting:
![Image](https://github.com/unc-csxl/csxl.unc.edu/assets/97476936/28ec96ea-1cba-4655-930b-497f7e5cad95)

## Why?
This must be resolved to ensure that the code may be compiled.

## Acceptance Criteria
- [ ] Update the linter to ensure that it autoformatting does not cause errors.

**Comment by ajaygandecha** [comment]
@KrisJordan, any ideas about this? Seems like it was just a bad idea to use ternary in this case - wondering if I can close this issue.

**Comment by KrisJordan** [comment]
I wonder if we can get the max length for the auto formatter and the linter to be equal, @atoneyd ? Otherwise, closing is ok. Probably should not be ternary, agreed.
