### ISSUE TITLE
Add Markdown Support to Event Details + Improve Event Details Card UX

### ISSUE THREAD

**Issue by jadekeegan** [unc-csxl/csxl.unc.edu#158]
# Improve Event Details Card UX
Fix the Event Details card styling to prevent text from running off the card. Add markdown to the event details card.

## Why?
These changes will ensure that the events and their information are displayed neatly and cleanly to the users. It will also provide organization leaders with improved features for writing their event descriptions!

## Acceptance Criteria
- [x] Fix text overflowing off of Event Details Card.
- [x] Add markdown capability to the description for the Event Details card.

**Comment by ajaygandecha** [comment]
Moved to #514
