### ISSUE TITLE
As Merritt Manager, I want to see and manage roles on a user's profile, so that I can better manage the site for an individual person.

### ISSUE THREAD

**Issue by KrisJordan** [unc-csxl/csxl.unc.edu#18]

**Comment by ajaygandecha** [comment]
@KrisJordan should this ticket be tabled?

**Comment by KrisJordan** [comment]
I'd actually still like to get an admin user editor going that enabled admin editing of roles and permissions.

I wonder if this should ultimately be folded into profiles or a user directory.

**Comment by ajaygandecha** [comment]
@KrisJordan, closing this ticket in favor of #428 .
