### ISSUE TITLE
As a CSXL developer, I want a well-factored solution for pagination in APIs and Angular, so I am not reinventing the wheel.

### ISSUE THREAD

**Issue by KrisJordan** [unc-csxl/csxl.unc.edu#20]
The basis for a pagination API to be factored out can be found here: 

* [Pagination Models Backend](https://github.com/unc-csxl/csxl.unc.edu/blob/c42dc98f54e2a50f6538d9a0a14c321b28f2ee97/backend/models/pagination.py#L8) 
* [Pagination Service Implementation](https://github.com/unc-csxl/csxl.unc.edu/blob/c42dc98f54e2a50f6538d9a0a14c321b28f2ee97/backend/services/user.py#L41)
* [Pagination in Angular](https://github.com/unc-csxl/csxl.unc.edu/blob/c42dc98f54e2a50f6538d9a0a14c321b28f2ee97/frontend/src/app/admin/users/list/admin-users-list.component.ts#L16)

**Comment by ajaygandecha** [comment]
@KrisJordan is this something that has been completed? Is this something that should be connected to @atoneyd's ticket in #130 ? Wondering if a fix might help her there.

**Comment by KrisJordan** [comment]
I need to review this code, do you know which branch?

**Comment by ajaygandecha** [comment]
@KrisJordan should be in #130 !

**Comment by ajaygandecha** [comment]
@KrisJordan closing issue and rewriting
