### ISSUE TITLE
Create User Selector Widget

### ISSUE THREAD

**Issue by ajaygandecha** [unc-csxl/csxl.unc.edu#225]
Create a user selector widget dropdown with chips in a similar design to the one in the old wireframe for coworking! This widget should take in a list of users from the user API, filter them based on the input, and allow users to be clicked on. Once clicked, chips will show up indicating the selected user(s). Users' profile pictures will also be shown.

**Comment by KrisJordan** [comment]
Does @jadekeegan latest work on event organizer selection resolve this?

**Comment by jadekeegan** [comment]
> Does @jadekeegan latest work on event organizer selection resolve this?

Functionality wise, yes. However, I need to convert it and the other organizer list from Event Details card to widgets. Will try to get that done today!
