### ISSUE TITLE
Community Agreement Form

### ISSUE THREAD

**Issue by KrisJordan** [unc-csxl/csxl.unc.edu#238]

**Comment by tmattvu** [comment]
Progress: 

- Added has_agreed field for user and profile models on frontend and backend to keep track of whether or not they accepted the community agreement
- Updated necessary API calls
- Added community agreement widget to shared folder
- Added community agreement widget to profile page where user can click on box to read community agreement
- Added working accept button in the pop up box
- FOR EXISTING USERS: When accessing home page of the csxl website, a pop up will show up with the agreement asking to accept if the user has not accepted yet
