### ISSUE TITLE
Community Slack Info

### ISSUE THREAD

**Issue by KrisJordan** [unc-csxl/csxl.unc.edu#239]
There should be a way to join the slack from the XL website for logged in users. There should be a brief community standards agreement (we have text for this in an airtable form). Importantly, users should be instructed on profile pic and real name expectations and then given a link to join the slack

**Comment by krohan03** [comment]
Progress

- Added content box in 'about' page for Slack invite and populated with basic info and button
- Created dialog box on button click for access to Slack invite
- Populated dialog box with information on community standards and Slack expectations
- Added a button with current dummy link for the Slack invite
- Configured dialog box to only appear when user is signed in
- Created alternate dialog box to appear when user is not signed in prompting them to sign in
- Formatted css

To-Do:

- Integrate Issue 239: Community Agreement Form after that issue's completion to automatically check if user has accepted community standard agreement
- Create dialog box prompting users to accept community agreement if they have not already
- Get Slack permalink (permalink can only be created by Slack admins)

**Comment by krohan03** [comment]
Progress:

- Slack integration has been completely moved from about page to a button bar on the bottom of the side navbar
- Widget has been moved and dialog box text has been updated
- Dialog box button moved to left side
- Slack permalink has been added
- Github button linking to code base also added to button bar
- Github button swaps between light/dark mode logos depending on browser settings
- Button bar only displays for signed-in users

To-Do:

- Integrate Issue 238: Community Agreement Form after that issue's completion to automatically check if user has accepted community standard agreement
- Integrate Issue 251: Feedback Buttons to add button to provide feedback into the bottom button bar in sidebar
- Finalize design preferences (monochrome vs color Slack logo, button bar positioning, etc.)
