### ISSUE TITLE
Add Feedback Buttons/Pages

### ISSUE THREAD

**Issue by jadekeegan** [unc-csxl/csxl.unc.edu#251]
# Add Feedback Buttons/Pages
Add buttons/pages for reporting issues or providing suggestions regarding the CSXL..

## Why?
This will provide users with the opportunity to interact with the CSXL and help us improve the space and site.

## Acceptance Criteria
- [ ] Confirm with Kris how he would like to handle reporting issues/giving feedback - do we want feedback to be internally available, or should we just link to an outside form?
    - [ ] Let @jadekeegan know what Kris decides if not already aware so acceptance criteria can be updated.
- [ ] Create a button to navigate to a suggestions form.
- [ ] ... further acceptance criteria TBA

**Comment by ajaygandecha** [comment]
@KrisJordan, are we still keeping this ticket open, or have we decided to let feedback remain in GitHub and in Slack?

**Comment by ajaygandecha** [comment]
@tmattvu closing this PR until we get #15 working.
