### ISSUE TITLE
Frontend Orientation Syntax Error

### ISSUE THREAD

**Issue by wokwen** [unc-csxl/csxl.unc.edu#258]
There is an error in the frontend typescript tutorial under "Class and Interface Construction".
In the Student class, the constructor signature says "constructor(name: string, year: int, adr: string)" instead of 
"constructor(name: string, year: number, adr: string)"

**Comment by KrisJordan** [comment]
Thanks for reporting this, can you instead open the ticket in the orientation repository: https://github.com/unc-csxl/orientation

Thanks!

**Comment by wokwen** [comment]
Sorry for reporting on the wrong repo. I have created the new ticket<https://github.com/unc-csxl/orientation/issues/12> for it and added another issue I came across.

Thanks!
[https://opengraph.githubassets.com/03480b7cfcfcb30813c14c648afd8302de920f1ed670abda8e0ebe3a55cbdb4c/unc-csxl/orientation/issues/12]<https://github.com/unc-csxl/orientation/issues/12>
Frontend Orientation Syntax Error · Issue #12 · unc-csxl/orientation<https://github.com/unc-csxl/orientation/issues/12>
There is an error in the frontend typescript tutorial under "Class and Interface Construction". In the Student class, the constructor signature says "constructor(name: string, year: int, adr: strin...
github.com


Wisdom Okwen, He/Him
Bsc. Computer Science, Statistics (Minor)
Honors Carolina '26
Residential Computing Consultant - ResNET
[cid:8709cd76-ed6d-4381-b292-c7c64e8b58ee]
________________________________
