### ISSUE TITLE
Migrate upcoming reservations up a level into Coworking

### ISSUE THREAD

**Issue by yuvrajjain2003** [unc-csxl/csxl.unc.edu#260]
# Why?

We need to move the user's upcoming reservations up a level so they are visible at the coworking level itself, since this makes it easier for a user to view their upcoming reservations at a glance. This also separates the upcoming and new reservations from being at the same level. 

# Acceptance Criteria

- [x] Move all upcoming reservation cards into the coworking level.
- [x] Condense the cards to only show relevant information. Only show the Room No, Date, and Time of the reservation along with the reservation ID.
- [x] Update the format to be consistent with the MAT UI. (Consistent with the rest of the CSXL codebase.)

**Comment by KrisJordan** [comment]
I believe the reservation data _should_ be coming in to the coworking home page already via the `get_coworking_status` endpoint:

https://github.com/unc-csxl/csxl.unc.edu/blob/93b43206ec44f3dd9d4c4b78ae069a76e967f682/backend/services/coworking/status.py#L34-L35

The `get_current_reservations_for_user` endpoint goes out through the `reservation_window` of the PolicyService (which is currently set to 1 week).
