### ISSUE TITLE
Add Documentation to Event Pagination Code

### ISSUE THREAD

**Issue by jadekeegan** [unc-csxl/csxl.unc.edu#290]
Add documentation to the backend/frontend code for event pagination.

**Comment by ajaygandecha** [comment]
Lol....

**Comment by ajaygandecha** [comment]
Hey @atoneyd / @jadekeegan, should I close this ticket?

I think pagination is going to be shaken up soon (as work on the exploration pagination refactoring branch continues), so we could table this and roll it into the larger pagination redo.

**Comment by atoneyd** [comment]
SGTM
