### ISSUE TITLE
As Sol Student, I would like to be able to check-in to the CSXL.

### ISSUE THREAD

**Issue by theyanaga** [unc-csxl/csxl.unc.edu#30]
This issue is for the implementation of check-in for the CSXL website. 

Ideally, we would like to have students sign-in by themselves through the CSXL website, discontinuing the AirTable form. 

## TODO - Add previews for UI idea.

**Comment by KrisJordan** [comment]
The high pri features here are:

1. Registration includes the community agreement
2. Ambassador role and tab for ambassadors to check folks in
3. Admins and ambassadors able to see a tab in the admin area on history of check ins and key stats 

Also of interest, but lower priority:

3. Any low hanging features for members to see their check in history / stats
4. Perhaps a public view in a co-working tab for how many folks have checked in recently, etc

**Comment by ajaygandecha** [comment]
@KrisJordan, should this ticket be tabled with the rollout of coworking?

**Comment by KrisJordan** [comment]
Yes, good call.
