### ISSUE TITLE
Fix Drop-in Draft Bug

### ISSUE THREAD

**Issue by JohnSchachte** [unc-csxl/csxl.unc.edu#326]
# Why?
- Sally the student should be able to navigagte away from a drop-in draft and make a new draft

# Acceptance Criteria:
- [ ] draft is cancelled in the reservation component when user navigates away from component

**Comment by KrisJordan** [comment]
This was closed by #356 - the cancellation of drafts works (and makes sense) from the room resi, but for drop-ins we will continue showing them on the coworking home page (until explicitly cancelled).
