### ISSUE TITLE
Show room capacity and type on new reservation page

### ISSUE THREAD

**Issue by aarjavjain2002** [unc-csxl/csxl.unc.edu#396]
# Why?
We want users to be able to click on the room names in the table which would open a dialogue box/ go to a page with the room's information. It should display the capacity of the room as well as the type of room ("Pairing Room", "Small Group", "Large Group").

**Comment by ajaygandecha** [comment]
@aarjavjain2002 / @yuvrajjain2003 / @wherthey Since #416 was closed, this can be re-done in a separate, standalone PR. I will also tag this as "Good First Issue".
