### ISSUE TITLE
Fix Duplicate HTTP Requests for Event Page Load

### ISSUE THREAD

**Issue by ajaygandecha** [unc-csxl/csxl.unc.edu#601]
Currently, loading the event page kicks off many duplicate HTTP requests. This may be a problem due to the effects.

*Consider what would happen if all pagination state variables were combined into one.*

**Comment by jadekeegan** [comment]
After further investigation, this isn't actually a bug. We just have to repoll the events when we go onto the page as the pagination parameters change.
