### ISSUE TITLE
Navigation bar title push profile button out of screen

### ISSUE THREAD

**Issue by mlouielu** [unc-csxl/csxl.unc.edu#607]
On my phone with larger font, the navigation bar title ( `navigationService.title`) will push profile button out of the screen, shown as the following figure:

<img src="https://github.com/user-attachments/assets/0f0d59ad-4ca1-4ad6-b183-94f2effe806a" width="240px" />

Possible fix:
Adding `overflow` and `text-overflow` at the element, either add it in `title-medium` or create a new css class to handle this.

<img src="https://github.com/user-attachments/assets/9883158d-ecac-4f0e-8547-938760f8510a" width="480px" />

**Comment by 12beesinatrenchcoat** [comment]
Didn't see this, but this might have been coincidentally resolved by https://github.com/unc-csxl/csxl.unc.edu/pull/637 (`text-overflow: ellipsis` added to title).

**Comment by mlouielu** [comment]
Fixed by #637
