### ISSUE TITLE
Login button looks like logout button

### ISSUE THREAD

**Issue by leferlito** [unc-csxl/csxl.unc.edu#623]
Especially bad on mobile - people are unable to find it

**Comment by 12beesinatrenchcoat** [comment]
(Hi, not a member of the team, but...) If I could throw a few ideas around:
1. Change the icon, maybe something like [account circle](https://fonts.google.com/icons?selected=Material+Symbols+Outlined%3Aaccount_circle%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024&icon.query=profile&icon.size=24&icon.color=%23e8eaed)
2. Keep the "Log in" text even on mobile (although there should be overflow considerations)
    - Sites like Google and GitHub do this.
    
And as this is marked "good first issue", could I try my hand at this?

**Comment by leferlito** [comment]
You are welcome to take any approach you like and put up a PR that people on the team will review.  We would love to see you try it!
