### ISSUE TITLE
Migrate Events Table (Backend)

### ISSUE THREAD

**Issue by jadekeegan** [unc-csxl/csxl.unc.edu#94]
# Migrate Events Table (Backend)
Add tags to the Events backend and migrate it over to the CSXL repository.

## Why?
Tags will be a nice enhancement to the current Events page to improve the filtering and design of the page as a whole. The Events page feature will be useful for organizations to display what events they have going on.

## Acceptance Criteria
- [x] Migrate over the API routes and service methods.
- [x] Migrate over the models/entities and dev data.
- [x] Update the models/entities to allow for events to be associated with one organization.
- [x] Ensure that only admin users can create or update events on the backend.

**Comment by ajaygandecha** [comment]
We can consider adding the logs table in this migration. Will link to #80
